services:
  go:
    build: ./go
    ports:
      - "9000:9000"
    environment:
      OTEL_RESOURCE_ATTRIBUTES: service.name=go-service,service.instance.id=localhost:9000
      OTEL_EXPORTER_OTLP_ENDPOINT: http://collector:4318
      OTEL_METRIC_EXPORT_INTERVAL: "5000"  # so we don't have to wait 60s for metrics
      KAFKA_BROKER: kafka:29092
    depends_on:
      kafka:
        condition: service_healthy

  collector:
    image: grafana/otel-lgtm:0.6.0
    ports:
      - "4317:4317"
      - "4318:4318"
      - "3000:3000"
    healthcheck:
      test: curl --silent --fail localhost:3000 || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
  
  kafka:
    container_name: kafka
    image: bitnami/kafka:3.7
    volumes:
      - ./otel/opentelemetry-javaagent.jar:/usr/share/java/opentelemetry-javaagent.jar
    environment:
      # KRaft settings
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      # Listeners
      KAFKA_CFG_LISTENERS: CONTROLLER://:9093,INTERNAL://:9092,EXTERNAL://:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://kafka:29092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      # JavaAgent of opentelemetry
      EXTRA_ARGS: "-Xms128m -Xmx256m -javaagent:/usr/share/java/opentelemetry-javaagent.jar -Dotel.jmx.target.system=kafka-broker -Dotel.resource.attributes=service.name=kafka-broker,service.instance.id=kafka:29092 -Dotel.exporter.otlp.endpoint=http://collector:4318"
    ports:
      - "29092:29092"
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions.sh", "--bootstrap-server", "localhost:29092"]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      collector:
        condition: service_healthy

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    volumes:
      - ./kafka-ui/config.yml:/etc/kafkaui/dynamic_config.yaml
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:8080 || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    depends_on:
      kafka:
        condition: service_healthy